### ISSUE TITLE
[question] why is core-js needed (as non-dev dependency) ?

### ISSUE THREAD

**Issue by mariusa** [martinussuherman/vue-template#15]
Hi,

https://github.com/martinussuherman/vue-template/blob/e900f9c2b5cfa7056abd3368bc9f9293f2e6045c/package.json#L11

why is core-js needed? It's not imported anywhere.

If needed, maybe should be in `devDependencies` ?

**Comment by martinussuherman** [comment]
Hi @mariusa,
core-js is one of the dependencies that you got when you create vue2 project via vue-cli, you can see that by looking at the first commit in this repo (at that commit it's just what you get from using vue-cli). So I can't answer exactly why it's needed. I'm sorry if I can't help much on this.

Regards,

Martinus

**Comment by mariusa** [comment]
Answer: it's not needed. I removed it from package.json and it works fine. It's still installed:
```
$ npm ls core-js
vue-template@1.1.0 /home/marius/work/misc/vue-template
└─┬ vite-plugin-vue2@1.4.3
  └─┬ babel-preset-env@1.7.0
    └─┬ babel-plugin-check-es2015-constants@6.22.0
      └─┬ babel-runtime@6.26.0
        └── core-js@2.6.12 
```

**Comment by martinussuherman** [comment]
Thanks @mariusa for the info. Really appreciate that :smile:

Regards, 

Martinus
