### ISSUE TITLE
sass-loader doesn't seem needed

### ISSUE THREAD

**Issue by mariusa** [martinussuherman/vue-template#17]
https://github.com/martinussuherman/vue-template/blob/e900f9c2b5cfa7056abd3368bc9f9293f2e6045c/package.json#L29

Just `sass` should be enough: https://vitejs.dev/guide/features.html#css-pre-processors

**Comment by martinussuherman** [comment]
Thanks for the info @mariusa. I'll test and update asap.

Regards,

Martinus
