### ISSUE TITLE
Cannot set a class property = @Prop value

### ISSUE THREAD

**Issue by jamesabell** [martinussuherman/vue-template#54]
Hey @martinussuherman,

Thanks for putting this together, I know this is just your template and has nothing to do with this repo, but wanted to get your take as maybe there's some kind of version issue here.

If you try to set a class property to a Vue property the class property will not be set. This is not the case when bundling with webpack (or other methods).

Example: 
```
<template>
  <div>
    <p>This works: {{ test }}</p>
    <p>This also works: {{ thisWorks }}</p>
    <p>This doesnt: {{ thisDoesnt }}</p>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";

@Component
export default class TestComponent extends Vue {
  @Prop({ default: "WORKS" }) input !: string;

  thisWorks = "WORKS!";
  thisDoesnt = this.input;
}
</script>
```

I've been spelunking in vue-property-decorator, but I can't see any reasoning for the change of behaviour. It seems likely that this may be a bug in esbuild, but would love to get your take. 

Should note that defining the prop in the @Component decorator works correctly, which is what made me focus on the the property decorator. 

Someone also opened an issue with this in vite-plugin-vue2: https://github.com/underfin/vite-plugin-vue2/issues/124 but I also don't think it's an issue with that.

Opening this issue here, so others see it if they are using this template.

**Comment by martinussuherman** [comment]
Thanks for the info @jamesabell, maybe this has to do with vite instead of vite-plugin-vue2?

**Comment by jamesabell** [comment]
@martinussuherman I'm not quite sure where to keep looking. 

Doing a bit more testing it seems like properties decorated with @Prop are not set as class properties in the constructor leading to this failing.

For example this does work (used in my example above):
`thisDoesnt = this.$props.input;`

**Comment by jamesabell** [comment]
Actually just found that if you set the property before the @Prop declaration it works... Seems really strange.

So this actually works because @Prop comes afterwards.
```
export default class TestComponent extends Vue {
  thisWorks = "WORKS!";
  thisDoesnt = this.input;
  
  @Prop({ default: "WORKS" }) input !: string;
}
```

**Comment by jamesabell** [comment]
I'm thinking this has to do with how tsc handles decorator metadata reflection, and esbuild doesn't by design.

I'm hoping this the only issue I run into with this setup. I'm currently trying to move a couple Vue 2 projects over to Vite. I will eventually be upgrading them to Vue 3 and wanted to take advantage of Vite's tooling and speed gains from esbuild.

I can live with updating to `this.$props.input` I think, I just hope this doesn't cause issues in any of the other package we use.

**Comment by jamesabell** [comment]
@martinussuherman Setting `useDefineForClassFields: false` in tsconfig compilerOptions fixes this issue :)

**Comment by martinussuherman** [comment]
Great, thanks for the info and the PR @jamesabell !
